// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DeviceTypeList struct {
	_tab flatbuffers.Table
}

func GetRootAsDeviceTypeList(buf []byte, offset flatbuffers.UOffsetT) *DeviceTypeList {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DeviceTypeList{}
	x.Init(buf, n+offset)
	return x
}

func FinishDeviceTypeListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDeviceTypeList(buf []byte, offset flatbuffers.UOffsetT) *DeviceTypeList {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DeviceTypeList{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDeviceTypeListBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DeviceTypeList) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeviceTypeList) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DeviceTypeList) Types(obj *DeviceType, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DeviceTypeList) TypesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func DeviceTypeListStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DeviceTypeListAddTypes(builder *flatbuffers.Builder, types flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(types), 0)
}
func DeviceTypeListStartTypesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DeviceTypeListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
